In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.3'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [6]:
df.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

In [8]:
pd.Series(df['fuel_type']).unique()

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

In [21]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [27]:
df.groupby('origin').max()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
origin,,,,,,,,,,
Asia,370,11.0,245.0,4661.144932,22.7,2023,Gasoline,Front-wheel drive,4.0,23.759123
Europe,380,13.0,271.0,4726.977269,23.5,2023,Gasoline,Front-wheel drive,3.0,25.967222
USA,380,13.0,252.0,4739.077089,24.3,2023,Gasoline,Front-wheel drive,3.0,24.971452

In [31]:
df['horsepower'].median()

np.float64(149.0)

In [39]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [42]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [43]:
df['horsepower'].median()

np.float64(152.0)

In [52]:
asia_df = df[df['origin'] == 'Asia'].loc[:, ['vehicle_weight', 'model_year']].head(7)

X = asia_df.values

X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [54]:
X_transpose = X.T

XTX = np.dot(X_transpose, X)

XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [60]:

XTX_inv = np.linalg.inv(XTX) 

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Теперь эта строчка отработает без ошибок
w = np.dot(np.dot(XTX_inv, X.T), y)

np.sum(w)

np.float64(0.5187709081074016)