In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = 'course_lead_scoring.csv'

In [3]:
df = pd.read_csv(data)

df.head()

,lead_source,industry,number_of_courses_viewed,annual_income,employment_status,location,interaction_count,lead_score,converted
0,paid_ads,NaN,1,79450.0,unemployed,south_america,4,0.94,1
1,social_media,retail,1,46992.0,employed,south_america,1,0.80,0
2,events,healthcare,5,78796.0,unemployed,australia,3,0.69,1
3,paid_ads,retail,2,83843.0,NaN,australia,1,0.87,0
4,referral,education,3,85012.0,self_employed,europe,3,0.62,1

In [4]:
df.isna().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [5]:
df.dtypes

lead_source                     str
industry                        str
number_of_courses_viewed      int64
annual_income               float64
employment_status               str
location                        str
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [6]:
df.nunique()

lead_source                    5
industry                       7
number_of_courses_viewed      10
annual_income               1267
employment_status              4
location                       7
interaction_count             12
lead_score                   101
converted                      2
dtype: int64

In [7]:
categorical = ['lead_source', 'industry', 'employment_status', 'location']
numerical = ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']

In [8]:
df[categorical] = df[categorical].fillna('NA')
df[numerical] = df[numerical].fillna(0.0)

In [9]:
df[numerical].nunique()

number_of_courses_viewed      10
annual_income               1268
interaction_count             12
lead_score                   101
dtype: int64

In [10]:
df[categorical].nunique()

lead_source          6
industry             8
employment_status    5
location             8
dtype: int64

In [11]:
df.industry.mode()

0    retail
Name: industry, dtype: str

To create a correlation matrix for the numerical features, let's create a separate DataFrame.

In [12]:
corr_matrix = df[numerical].corr()
corr_matrix

,number_of_courses_viewed,annual_income,interaction_count,lead_score
number_of_courses_viewed,1.000000,0.009770,-0.023565,-0.004879
annual_income,0.009770,1.000000,0.027036,0.015610
interaction_count,-0.023565,0.027036,1.000000,0.009888
lead_score,-0.004879,0.015610,0.009888,1.000000

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.

stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.

Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.

    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]

>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]

>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]

>>> from sklearn import datasets
>>> iris = datasets.load_iris(as_frame=True)
>>> X, y = iris['data'], iris['target']
>>> X.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
>>> y.head()
0    0
1    0
2    0
3    0
4    0
...

>>> X_train, X_test, y_train, y_test = train_test_split(
... X, y, test_size=0.33, random_state=42)
...
>>> X_train.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                 5.7               2.9                4.2               1.3
105                7.6               3.0                6.6               2.1
66                 5.6               3.0                4.5               1.5
0                  5.1               3.5                1.4               0.2
122                7.7               2.8                6.7               2.0
>>> y_train.head()
96     1
105    2
66     1
0      0
122    2
...
>>> X_test.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
>>> y_test.head()
73     1
18     0
118    2
78     1
76     1
...
File:      c:\users\ruste\onedrive\рабочий стол\stuff\hmm\.venv\lib\site-packages\sklearn\model_selection\_split.py
Type:      function

In [15]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

len(df_train), len(df_val), len(df_test), len(df_full_train)

(876, 293, 293, 1169)

In [16]:
df_train = df_train.reset_index(drop=True)
df_val =df_val.reset_index(drop=True)
df_test= df_test.reset_index(drop=True)

y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']

In [17]:
from sklearn.metrics import mutual_info_score

def mut_info_converted(series):
    return round(mutual_info_score(series, y_train), 2)

mi = df_train[categorical].apply(mut_info_converted)
mi.sort_values(ascending=False)

lead_source          0.04
industry             0.01
employment_status    0.01
location             0.00
dtype: float64

### time to use the logistic regression

```python

def sigmoid:
    return 1 / (1 + np.exp(-z))

def logistic_regression:
    score = w0

    for j in range(len(xi)):
        score = score + xi[j] * w[j]

    result = sigmoid(score)
    return result
```

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer

In [19]:
model = LogisticRegression(solver = 'liblinear', C=1.0, max_iter=1000, random_state = 42)
dv = DictVectorizer(sparse=False)

train_dicts = df_train[categorical + numerical].to_dict(orient='records')
val_dicts = df_val[categorical + numerical].to_dict(orient='records')

In [20]:
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)


model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [21]:
y_pred = model.predict_proba(X_val)[:, 1]
converted_decision = (y_pred >= 0.5)


original_accuracy = (y_val == converted_decision).mean()

round((y_val == converted_decision).mean(),2)

np.float64(0.7)

### Now, let's do the feature elimination part. 
We have as our initial accuracy of our model 70%. By removing each feature separately, we will compare the accuracy and conclude what shall we remove.

industry, employment_status, lead_score?

In [34]:
train_dicts = df_train[categorical + numerical].drop(columns=['industry']).to_dict(orient='records')
val_dicts = df_val[categorical + numerical].drop(columns=['industry']).to_dict(orient='records')

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)


model.fit(X_train, y_train)

y_pred = model.predict_proba(X_val)[:, 1]
converted_decision = (y_pred >= 0.5)

abs(original_accuracy - (y_val == converted_decision).mean()) # Excluded 'industry' feature

np.float64(0.0)

In [35]:
train_dicts = df_train[categorical + numerical].drop(columns=['employment_status']).to_dict(orient='records')
val_dicts = df_val[categorical + numerical].drop(columns=['employment_status']).to_dict(orient='records')

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)


model.fit(X_train, y_train)

y_pred = model.predict_proba(X_val)[:, 1]
converted_decision = (y_pred >= 0.5)

abs(original_accuracy - (y_val == converted_decision).mean()) # Excluded 'employment_status' feature

np.float64(0.0034129692832763903)

In [36]:
train_dicts = df_train[categorical + numerical].drop(columns=['lead_score']).to_dict(orient='records')
val_dicts = df_val[categorical + numerical].drop(columns=['lead_score']).to_dict(orient='records')

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)


model.fit(X_train, y_train)

y_pred = model.predict_proba(X_val)[:, 1]
converted_decision = (y_pred >= 0.5)

abs(original_accuracy - (y_val == converted_decision).mean()) # Excluded 'lead_score' feature

np.float64(0.0068259385665528916)

We see, that the least impactful feature is industry, so in real scenarios, it is better to avoid using that feature in the training dataset.

In [46]:
train_dicts = df_train[categorical + numerical].to_dict(orient='records')
val_dicts = df_val[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

for regul in [0.01, 0.1, 1, 10, 100]:
    model = LogisticRegression(solver='liblinear', C=regul, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    converted_decision = (y_pred >= 0.5)
    accuracy = (y_val == converted_decision).mean()
    print(y_pred[:5])

    print(regul, accuracy, sep='\n')
    print()

[0.61192389 0.78000585 0.5269044  0.46836272 0.56737315]
0.01
0.6996587030716723

[0.61193591 0.79790031 0.52976761 0.47097629 0.57026821]
0.1
0.6996587030716723

[0.61192163 0.79982617 0.53021344 0.47131479 0.57066131]
1
0.6996587030716723

[0.61192003 0.80002017 0.53025988 0.47134953 0.57070183]
10
0.6996587030716723

[0.61191986 0.80003958 0.53026453 0.47135301 0.57070588]
100
0.6996587030716723

In [44]:
print(y_val.mean())
print(converted_decision.mean())

0.5563139931740614
0.8020477815699659

In [45]:
print(y_pred[:5])

[0.61191986 0.80003958 0.53026453 0.47135301 0.57070588]

The features in this dataset have very weak predictive signal (MI scores near 0, correlations near 0). Because of that, the model's weights stay small regardless of how strong or weak the regularization is. Different C values shift the raw probabilities slightly, but never enough to push any sample across the 0.5 decision boundary — so the binary classifications end up identical for all five models.