In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = 'credit_card_default.xls'

In [3]:
df = pd.read_excel(data)

In [4]:
df.head()

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0

In [5]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

new_columns = list(df.iloc[0].values)
new_columns[0] = 'id'
df.columns = new_columns
df = df.drop(df.index[0]).reset_index(drop=True)

In [6]:
df.head().T

                                0       1      2      3      4
ID                              1       2      3      4      5
LIMIT_BAL                   20000  120000  90000  50000  50000
SEX                             2       2      2      2      1
EDUCATION                       2       2      2      2      2
MARRIAGE                        1       2      2      1      1
AGE                            24      26     34     37     57
PAY_0                           2      -1      0      0     -1
PAY_2                           2       2      0      0      0
PAY_3                          -1       0      0      0     -1
PAY_4                          -1       0      0      0      0
PAY_5                          -2       0      0      0      0
PAY_6                          -2       2      0      0      0
BILL_AMT1                    3913    2682  29239  46990   8617
BILL_AMT2                    3102    1725  14027  48233   5670
BILL_AMT3                     689    2682  13559  49291  35835
BILL_AMT4                       0    3272  14331  28314  20940
BILL_AMT5                       0    3455  14948  28959  19146
BILL_AMT6                       0    3261  15549  29547  19131
PAY_AMT1                        0       0   1518   2000   2000
PAY_AMT2                      689    1000   1500   2019  36681
PAY_AMT3                        0    1000   1000   1200  10000
PAY_AMT4                        0    1000   1000   1100   9000
PAY_AMT5                        0       0   1000   1069    689
PAY_AMT6                        0    2000   5000   1000    679
default payment next month      1       1      0      0      0

In [7]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [8]:
df = df.drop(columns=['ID'])

In [9]:
df.isna().sum()

limit_bal                     0
sex                           0
education                     0
marriage                      0
age                           0
pay_0                         0
pay_2                         0
pay_3                         0
pay_4                         0
pay_5                         0
pay_6                         0
bill_amt1                     0
bill_amt2                     0
bill_amt3                     0
bill_amt4                     0
bill_amt5                     0
bill_amt6                     0
pay_amt1                      0
pay_amt2                      0
pay_amt3                      0
pay_amt4                      0
pay_amt5                      0
pay_amt6                      0
default_payment_next_month    0
dtype: int64

In [10]:
df

,limit_bal,sex,education,marriage,age,pay_0,pay_2,pay_3,pay_4,pay_5,...,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6,default_payment_next_month
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000,1,3,1,39,0,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,150000,1,3,2,43,-1,-1,-1,-1,0,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,30000,1,2,2,37,4,3,2,-1,0,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,80000,1,3,1,41,1,-1,0,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,50000,1,2,1,46,0,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [12]:
list(df.columns)

['limit_bal',
 'sex',
 'education',
 'marriage',
 'age',
 'pay_0',
 'pay_2',
 'pay_3',
 'pay_4',
 'pay_5',
 'pay_6',
 'bill_amt1',
 'bill_amt2',
 'bill_amt3',
 'bill_amt4',
 'bill_amt5',
 'bill_amt6',
 'pay_amt1',
 'pay_amt2',
 'pay_amt3',
 'pay_amt4',
 'pay_amt5',
 'pay_amt6',
 'default_payment_next_month']

In [11]:
df.nunique()

limit_bal                        81
sex                               2
education                         7
marriage                          4
age                              56
pay_0                            11
pay_2                            11
pay_3                            11
pay_4                            11
pay_5                            10
pay_6                            10
bill_amt1                     22723
bill_amt2                     22346
bill_amt3                     22026
bill_amt4                     21548
bill_amt5                     21010
bill_amt6                     20604
pay_amt1                       7943
pay_amt2                       7899
pay_amt3                       7518
pay_amt4                       6937
pay_amt5                       6897
pay_amt6                       6939
default_payment_next_month        2
dtype: int64

In [20]:
categorical = ['sex', 'education', 'marriage', 'pay_0', 'pay_2', 'pay_3', 'pay_4', 'pay_5', 'pay_6']
numerical = ['limit_bal', 'age', 'bill_amt1', 'bill_amt2', 'bill_amt3', 'bill_amt4', 'bill_amt5', 'bill_amt6',
             'pay_amt1', 'pay_amt2', 'pay_amt3', 'pay_amt4', 'pay_amt5', 'pay_amt6']

# Our target variable is default_payment_next_month

In [14]:
corr_matrix = df[numerical].corr()
corr_matrix

,limit_bal,age,bill_amt1,bill_amt2,bill_amt3,bill_amt4,bill_amt5,bill_amt6,pay_amt1,pay_amt2,pay_amt3,pay_amt4,pay_amt5,pay_amt6
limit_bal,1.000000,0.144713,0.285430,0.278314,0.283236,0.293988,0.295562,0.290389,0.195236,0.178408,0.210167,0.203242,0.217202,0.219595
age,0.144713,1.000000,0.056239,0.054283,0.053710,0.051353,0.049345,0.047613,0.026147,0.021785,0.029247,0.021379,0.022850,0.019478
bill_amt1,0.285430,0.056239,1.000000,0.951484,0.892279,0.860272,0.829779,0.802650,0.140277,0.099355,0.156887,0.158303,0.167026,0.179341
bill_amt2,0.278314,0.054283,0.951484,1.000000,0.928326,0.892482,0.859778,0.831594,0.280365,0.100851,0.150718,0.147398,0.157957,0.174256
bill_amt3,0.283236,0.053710,0.892279,0.928326,1.000000,0.923969,0.883910,0.853320,0.244335,0.316936,0.130011,0.143405,0.179712,0.182326
bill_amt4,0.293988,0.051353,0.860272,0.892482,0.923969,1.000000,0.940134,0.900941,0.233012,0.207564,0.300023,0.130191,0.160433,0.177637
bill_amt5,0.295562,0.049345,0.829779,0.859778,0.883910,0.940134,1.000000,0.946197,0.217031,0.181246,0.252305,0.293118,0.141574,0.164184
bill_amt6,0.290389,0.047613,0.802650,0.831594,0.853320,0.900941,0.946197,1.000000,0.199965,0.172663,0.233770,0.250237,0.307729,0.115494
pay_amt1,0.195236,0.026147,0.140277,0.280365,0.244335,0.233012,0.217031,0.199965,1.000000,0.285576,0.252191,0.199558,0.148459,0.185735
pay_amt2,0.178408,0.021785,0.099355,0.100851,0.316936,0.207564,0.181246,0.172663,0.285576,1.000000,0.244770,0.180107,0.180908,0.157634
pay_amt3,0.210167,0.029247,0.156887,0.150718,0.130011,0.300023,0.252305,0.233770,0.252191,0.244770,1.000000,0.216325,0.159214,0.162740
pay_amt4,0.203242,0.021379,0.158303,0.147398,0.143405,0.130191,0.293118,0.250237,0.199558,0.180107,0.216325,1.000000,0.151830,0.157834
pay_amt5,0.217202,0.022850,0.167026,0.157957,0.179712,0.160433,0.141574,0.307729,0.148459,0.180908,0.159214,0.151830,1.000000,0.154896
pay_amt6,0.219595,0.019478,0.179341,0.174256,0.182326,0.177637,0.164184,0.115494,0.185735,0.157634,0.162740,0.157834,0.154896,1.000000

In [15]:
from sklearn.model_selection import train_test_split

In [21]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state = 42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state = 42)

len(df_train), len(df_val), len(df_test)

(18000, 6000, 6000)

In [22]:
df_train = df_train.reset_index(drop=True)
df_val =df_val.reset_index(drop=True)
df_test= df_test.reset_index(drop=True)

y_train = df_train.default_payment_next_month
y_val = df_val.default_payment_next_month
y_test = df_test.default_payment_next_month

del df_train['default_payment_next_month']
del df_val['default_payment_next_month']
del df_test['default_payment_next_month']

In [23]:
from sklearn.metrics import mutual_info_score

def mut_info_target(series):
    return mutual_info_score(series, y_train)

mi = df_train[categorical].apply(mut_info_target)

mi.sort_values(ascending=False)

pay_0        0.078020
pay_2        0.051223
pay_3        0.037988
pay_4        0.033288
pay_5        0.030084
pay_6        0.026560
education    0.002985
sex          0.000832
marriage     0.000627
dtype: float64

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction import DictVectorizer

model = LogisticRegression(solver='liblinear', random_state = 42, max_iter=30000)
dv = DictVectorizer(sparse=False)

train_dicts = df_train[categorical + numerical].to_dict(orient='records')
val_dicts = df_val[categorical + numerical].to_dict(orient='records')

In [32]:
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

model.fit(X_train, y_train)

LogisticRegression(max_iter=30000, random_state=42, solver='liblinear')

In [38]:
y_pred = model.predict_proba(X_val)[:, 1]
default_decision = (y_pred >= 0.5)

original_accuracy = (y_val == default_decision).mean()

original_accuracy

np.float64(0.7806666666666666)

now, let's get rid of most useless features and check our accuracy.
in mutual_info_score, we see that marriage, sex - variables with the lowest score.

In [39]:
train_dicts = df_train[categorical + numerical].drop(columns=['marriage']).to_dict(orient='records')
val_dicts = df_val[categorical + numerical].drop(columns=['marriage']).to_dict(orient='records')

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

model.fit(X_train, y_train)
y_pred = model.predict_proba(X_val)[:, 1]

new_decision = (y_pred >= 0.5)
new_accuracy = (y_val == new_decision).mean()

abs(original_accuracy - new_accuracy)

np.float64(0.0)

In [40]:
train_dicts = df_train[categorical + numerical].drop(columns=['sex']).to_dict(orient='records')
val_dicts = df_val[categorical + numerical].drop(columns=['sex']).to_dict(orient='records')

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

model.fit(X_train, y_train)
y_pred = model.predict_proba(X_val)[:, 1]

new_decision = (y_pred >= 0.5)
new_accuracy = (y_val == new_decision).mean()

abs(original_accuracy - new_accuracy)

np.float64(0.0)

In [41]:
train_dicts = df_train[categorical + numerical].drop(columns=['education']).to_dict(orient='records')
val_dicts = df_val[categorical + numerical].drop(columns=['education']).to_dict(orient='records')

X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

model.fit(X_train, y_train)
y_pred = model.predict_proba(X_val)[:, 1]

new_decision = (y_pred >= 0.5)
new_accuracy = (y_val == new_decision).mean()

abs(original_accuracy - new_accuracy)

np.float64(0.0)

since these features have such a low prediction score, they don't impact on the decision since it doesn't cross the threshold of 0.5

In [43]:
train_dicts = df_train[categorical + numerical].to_dict(orient='records')
val_dicts = df_val[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

for regularization in [0.01, 0.1, 1, 10, 100]:
    model = LogisticRegression(solver='liblinear', C=regularization, max_iter = 1000, random_state = 42)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    default_decision = (y_pred >= 0.5)
    accuracy = (y_val == default_decision).mean()
    print(y_pred[:5])

    print(regularization, accuracy, sep='\n')
    print()

[0.04943985 0.39057215 0.26604012 0.25351919 0.15940537]
0.01
0.7806666666666666

[0.04239934 0.40896278 0.30002084 0.25668816 0.15723542]
0.1
0.7806666666666666

[0.04567595 0.40006498 0.28321534 0.25509598 0.15856252]
1
0.7806666666666666

[0.04485443 0.40229    0.28779985 0.2557412  0.15803571]
10
0.7806666666666666

[0.03347539 0.4352141  0.351492   0.26043562 0.15292689]
100
0.7806666666666666

Varying the regularization strength ($C$) alone is not sufficient to overcome the underlying class imbalance or the lack of feature scaling. While the individual probability distributions shift slightly, the changes are too minor to push any predictions across the default 0.5 decision threshold.